name: DeluxeCoinflip
version: '${version}'
main: net.zithium.deluxecoinflip.DeluxeCoinflipPlugin
authors: [ ItzSave, ItsLewizzz, ItsSimplyLeo ]
api-version: 1.19
folia-supported: true

softdepend:
  - PlaceholderAPI
  - Vault
  - TokenEnchant
  - TokenManager
  - Essentials
  - ZithiumMobcoins

permissions:
  coinflip.admin:
    default: op
